### ISSUE TITLE
Provider Information is not set in the Manifest file (Samsung Galaxy J7)

### ISSUE THREAD

**Issue by Businessmancps** [Businessmancps/Cameraapp#1]
System.ArgumentException: Unable to get file location. This most likely means that the file provider information is not set in your Android Manifest file. Please check documentation on how to set this up in your project. ---> Java.Lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
  at Java.Interop.JniEnvironment+StaticMethods.CallStaticObjectMethod (Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00069] in <42bcf67b56bc4c909c2a5edee682522b>:0
  at Java.Interop.JniPeerMembers+JniStaticMethods.InvokeObjectMethod (System.String encodedMember, Java.Interop.JniArgumentValue* parameters) [0x00018] in <42bcf67b56bc4c909c2a5edee682522b>:0
  at Android.Support.V4.Content.FileProvider.GetUriForFile (Android.Content.Context context, System.String authority, Java.IO.File file) [0x00070] in <fb0c55a748614587b658fc2ca38fdfc2>:0
  at Plugin.Media.MediaPickerActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x0025b] in <5939e997f291496f805023da28f3a447>:0
  at java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
  at at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:591)
  at at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:565)
  at at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:403)
  at at md54cd65ac53ae710bff80022afc423e0f3.MediaPickerActivity.n_onCreate(Native Method)
  at at md54cd65ac53ae710bff80022afc423e0f3.MediaPickerActivity.onCreate(MediaPickerActivity.java:42)
  at at android.app.Activity.performCreate(Activity.java:7340)
  at at android.app.Activity.performCreate(Activity.java:7331)
  at at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1275)
  at at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3119)
  at at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3282)
  at at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
  at at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
  at at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
  at at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1970)
  at at android.os.Handler.dispatchMessage(Handler.java:106)
  at at android.os.Looper.loop(Looper.java:214)
  at at android.app.ActivityThread.main(ActivityThread.java:7156)
  at at java.lang.reflect.Method.invoke(Native Method)
  at at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
  at at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
  --- End of inner exception stack trace ---
  at Plugin.Media.MediaPickerActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x002d9] in <5939e997f291496f805023da28f3a447>:0
  at Plugin.Media.MediaImplementation.TakePhotoAsync (Plugin.Media.Abstractions.StoreCameraMediaOptions options) [0x00112] in <5939e997f291496f805023da28f3a447>:0
  at PhotoLibrary.PhotoLibraryActivity.TakePictureButton_Clicked (System.Object sender, System.EventArgs args) [0x001b4] in /Users/danielarchibald/Projects/PhotoLibrary/PhotoLibrary/PhotoLibraryActivity.cs:56
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in <6de48997d0c0445dbea8d4d83492d8c6>:0
  at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in <e88d856196084f13bf16b2c255e8952d>:0
  at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <e88d856196084f13bf16b2c255e8952d>:0
  at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in <e88d856196084f13bf16b2c255e8952d>:0
  at at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.6(intptr,intptr)

Permissions are set not quit sure whats causing the issue.

**Comment by Businessmancps** [comment]
This is whenever I try to access the rear camera.

**Comment by Businessmancps** [comment]
Read me text instructs to update the Manifest and solution files as follows

Media Plugin for Xamarin & Windows

Changelog:
[2.6.0]
* All: Ensure you call await CrossMedia.Current.Initialize(); before accessing any APIs
* All: Resize when taking a photo
* All: Save original album location when picking photo
* iOS & Android: Ability to resize when picking photo
* iOS & Android: Set Quality Level when taking photo
* Android: Fix images that get rotated in the wrong direction
* Android: Updates for Android N Strict Mode, see documentation if you target N+
* iOS & Android: Fix for rotating device.
* iOS: Added custom overlay method (Preview)
* iOS: iOS 10 support for new permissions, please see documentations
* Windows RT: Bug fixes & Video Support

Find the latest at: https://github.com/jamesmontemagno/MediaPlugin

## Additional Required Setup (Please Read!)

## Android 
In  your BaseActivity or MainActivity (for Xamarin.Forms) add this code:

public override void OnRequestPermissionsResult(int requestCode, string[] permissions, Permission[] grantResults)
{
    PermissionsImplementation.Current.OnRequestPermissionsResult(requestCode, permissions, grantResults);
}

The `WRITE_EXTERNAL_STORAGE`, `READ_EXTERNAL_STORAGE` permissions are required, but the library will automatically add this for you. Additionally, if your users are running Marshmallow the Plugin will automatically prompt them for runtime permissions.

Additionally, the following has been added for you:
[assembly: UsesFeature("android.hardware.camera", Required = false)]
[assembly: UsesFeature("android.hardware.camera.autofocus", Required = false)]

**ANDROID N**
If your application targets Android N (API 24) or newer, you must use version 2.6.0+.

You must also add a few additional configuration files to adhere to the new strict mode:

1.) Add the following to your AndroidManifest.xml inside the <application> tags:

<provider android:name="android.support.v4.content.FileProvider" 
				android:authorities="YOUR_APP_PACKAGE_NAME.fileprovider" 
				android:exported="false" 
				android:grantUriPermissions="true">
			<meta-data android:name="android.support.FILE_PROVIDER_PATHS" 
				android:resource="@xml/file_paths"></meta-data>
</provider>

YOUR_APP_PACKAGE_NAME must be set to your app package name!

2.) Add a new folder called xml into your Resources folder and add a new XML file called `file_paths.xml`

Add the following code:

<?xml version="1.0" encoding="utf-8"?>
<paths xmlns:android="http://schemas.android.com/apk/res/android">
    <external-path name="my_images" path="Android/data/YOUR_APP_PACKAGE_NAME/files/Pictures" />
    <external-path name="my_movies" path="Android/data/YOUR_APP_PACKAGE_NAME/files/Movies" />
</paths>

YOUR_APP_PACKAGE_NAME must be set to your app package name!

You can read more at: https://developer.android.com/training/camera/photobasics.html


### iOS

Your app is required to have keys in your Info.plist for `NSCameraUsageDescription` and `NSPhotoLibraryUsageDescription` in order to access the device's camera and photo/video library. If you are using the Video capabilities of the library then you must also add `NSMicrophoneUsageDescription`.  The string that you provide for each of these keys will be displayed to the user when they are prompted to provide permission to access these device features. You can read me here: https://blog.xamarin.com/new-ios-10-privacy-permission-settings/

Such as:
<key>NSCameraUsageDescription</key>
<string>This app needs access to the camera to take photos.</string>
<key>NSPhotoLibraryUsageDescription</key>
<string>This app needs access to photos.</string>
<key>NSMicrophoneUsageDescription</key>
<string>This app needs access to microphone.</string>

### Windows Phone 8/8.1 Silverlight

You must set the `IC_CAP_ISV_CAMERA` permission.

WP 8/8.1 Silverlight only supports photo, not video.

### Windows Phone 8.1 RT
Set `Webcam` permission.

In your App.xaml.cs you MUST place the following code inside of the `OnLaunched` method:

```csharp
protected override void OnActivated(IActivatedEventArgs args)
{

    Plugin.Media.MediaImplementation.OnFilesPicked(args);

    base.OnActivated(args);
}
```



### Windows Store:
Set `Webcam` permission.
